### ISSUE TITLE
Optimize pom.xml

### ISSUE THREAD

**Issue by zuston** [opendataio/hcfsfuse#27]
Thanks for your great work! 
I have few questions on it.

1. I think there is no need to import spring related dependencies.

2. Why not using maven shade plugin. Because when i use hcfsuse to mount hdfs, found that i can't get the hdfs filesystem through Java SPI. related question: https://stackoverflow.com/questions/17265002/hadoop-no-filesystem-for-scheme-file. When i refactor the way of packaging, it works well.

**Comment by zuston** [comment]
@maobaolong Please check it. Thanks~

**Comment by maobaolong** [comment]
@zuston Thanks for interest in `hcfsfuse`, will check it.

**Comment by zuston** [comment]
Solved https://github.com/opendataio/hcfsfuse/pull/28
