### ISSUE TITLE
mount fail when exec using a non-privileged user

### ISSUE THREAD

**Issue by ilovesxl** [opendataio/hcfsfuse#35]
jar /tmp/hcfsfuse-1.0.0-SNAPSHOT.jar -m /tmp/m3 -r hdfs://XXXX
ls /tmp

and i got:

d?????????  ? ?             ?                     ?            ?         m3

**Comment by maobaolong** [comment]
Maybe the user of children inode of `/tmp` is not exist in your current node, is it the reason?

**Comment by maobaolong** [comment]
@ilovesxl Is this issue still exist in your env? If not, i will close this issue, please feel free to reopen this ticket if this issue is still exist.
