### ISSUE TITLE
How to mount to a S3 endpoint

### ISSUE THREAD

**Issue by SunskyF** [opendataio/hcfsfuse#37]
I have a S3 bucket and I want to use hcfsfuse to mount a local directory to the bucket.
But I can't find the way to this thing. Please give me some help.
Thank you

**Comment by maobaolong** [comment]
You can execute the following command 

```
java -Dlog4j.configuration=file:<LOG4j_FILE_PATH> -jar target/hcfsfuse-1.0.0-SNAPSHOT-jar-with-dependencies.jar -c core-site.xml -c another-site.xml -m /Users/mbl/fusefs -r s3://bucket1/
```

**Comment by SunskyF** [comment]
Thanks for your response!
